name: Build Docker Image
description: This action builds a Docker image for the project
inputs:
  path_dockerfile:
    description:  "This allows us to locate the correct Dockerfile, even if it has a different name or is located in a different directory."
    required: false
    default: "Dockefile"
  image_name:
    description: "Replace-With-Your-Input-Description"
    required: true
  tag_name:
    description: "Replace-With-Your-Input-Description"
    required: false
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag_name }}"
        fi

        docker build . --file Dockerfile --tag ${{ inputs.image_name }}:$TAG
      shell: bash